apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zahmaola-secrets
  namespace: zahmaola
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: zahmaola-secrets
    creationPolicy: Owner
  data:
    - secretKey: AIL_MAILER
      remoteRef:
        key: zahmaola/secrets
        property: AIL_MAILER
    - secretKey: MAIL_HOST
      remoteRef:
        key: zahmaola/secrets
        property: MAIL_HOST
    - secretKey: MAIL_PORT
      remoteRef:
        key: zahmaola/secrets
        property: MAIL_PORT
    - secretKey: MAIL_USERNAME
      remoteRef:
        key: zahmaola/secrets
        property: MAIL_USERNAME
    - secretKey: MAIL_PASSWORD
      remoteRef:
        key: zahmaola/secrets
        property: MAIL_PASSWORD
    - secretKey: MAIL_ENCRYPTION
      remoteRef:
        key: zahmaola/secrets
        property: MAIL_ENCRYPTION
    - secretKey: MAIL_FROM_ADDRESS
      remoteRef:
        key: zahmaola/secrets
        property: MAIL_FROM_ADDRESS
    - secretKey: SMS_TOKEN
      remoteRef:
        key: zahmaola/secrets
        property: SMS_TOKEN
    - secretKey: PROJECT_ID
      remoteRef:
        key: zahmaola/secrets
        property: PROJECT_ID
    - secretKey: PROJECT_LOCATION
      remoteRef:
        key: zahmaola/secrets
        property: PROJECT_LOCATION
    - secretKey: QUEUE_NAME
      remoteRef:
        key: zahmaola/secrets
        property: QUEUE_NAME
    - secretKey: DB_HOST
      remoteRef:
        key: zahmaola/secrets
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: zahmaola/secrets
        property: DB_PORT
    - secretKey: DB_USERNAME
      remoteRef:
        key: zahmaola/secrets
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: zahmaola/secrets
        property: DB_PASSWORD
    - secretKey: DB_DATABASE
      remoteRef:
        key: zahmaola/secrets
        property: DB_DATABASE
    - secretKey: type
      remoteRef:
        key: zahmaola/secrets
        property: type
    - secretKey: project_id
      remoteRef:
        key: zahmaola/secrets
        property: project_id
    - secretKey: private_key_id
      remoteRef:
        key: zahmaola/secrets
        property: private_key_id
    - secretKey: private_key
      remoteRef:
        key: zahmaola/secrets
        property: private_key
    - secretKey: client_email
      remoteRef:
        key: zahmaola/secrets
        property: client_email
    - secretKey: client_id
      remoteRef:
        key: zahmaola/secrets
        property: client_id
    - secretKey: auth_uri
      remoteRef:
        key: zahmaola/secrets
        property: auth_uri
    - secretKey: token_uri
      remoteRef:
        key: zahmaola/secrets
        property: token_uri
    - secretKey: auth_provider_x509_cert_url
      remoteRef:
        key: zahmaola/secrets
        property: auth_provider_x509_cert_url
    - secretKey: client_x509_cert_url
      remoteRef:
        key: zahmaola/secrets
        property: client_x509_cert_url
    - secretKey: GCP_PROJECT_ID
      remoteRef:
        key: zahmaola/secrets
        property: GCP_PROJECT_ID
    - secretKey: TZ
      remoteRef:
        key: zahmaola/secrets
        property: TZ
    - secretKey: MINIO_ENDPOINT
      remoteRef:
        key: zahmaola/secrets
        property: MINIO_ENDPOINT
    - secretKey: MINIO_ACCESSKEY
      remoteRef:
        key: zahmaola/secrets
        property: MINIO_ACCESSKEY
    - secretKey: MINIO_SECRETKEY
      remoteRef:
        key: zahmaola/secrets
        property: MINIO_SECRETKEY
    - secretKey: MINIO_BUCKET
      remoteRef:
        key: zahmaola/secrets
        property: MINIO_BUCKET
    - secretKey: USE_SSL
      remoteRef:
        key: zahmaola/secrets
        property: USE_SSL
    - secretKey: firebase_admin_sdk_authentication
      remoteRef:
        key: zahmaola/secrets
        property: firebase_admin_sdk_authentication
    - secretKey: GOOGLE_API_KEY
      remoteRef:
        key: zahmaola/secrets
        property: GOOGLE_API_KEY
