apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-secret
  namespace: zahmaola
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ghcr-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: '{"auths":{"https://ghcr.io":{"username":"{{ .dockerusername }}","password":"{{ .dockerpassword }}","email":"{{ .dockeremail }}","auth":"{{ printf "%s:%s" .dockerusername .dockerpassword | b64enc }}"}}}'
  data:
    - secretKey: dockerusername
      remoteRef:
        key: ghcr
        property: docker-username
    - secretKey: dockerpassword
      remoteRef:
        key: ghcr
        property: docker-password
    - secretKey: dockeremail
      remoteRef:
        key: ghcr
        property: docker-email